uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_apachesolr650/static/source/apachesolr650.udb org.apache.solr
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_corendalwiki302/static/source/corendalwiki302.udb com.corendal
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_endeavour125/static/source/endeavour125.udb org.endeavour
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_freemind100/static/source/freemind100.udb freemind
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_jedit520/static/source/jedit520.udb org
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_jedit540/static/source/jedit540.udb org
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_jforum219/static/source/jforum219.udb net.jforum
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_jhotdraw76/static/source/jhotdraw76.udb org.jhotdraw
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_jpetstore6/static/source/jpetstore6.udb org
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_opensyncro22/static/source/opensyncro22.udb smilehouse
uperl newIntfAndParaClass.pl  ../RS17_source_data/RS17_weka381/static/source/weka381.udb weka
